name: Format check on pull request
on: pull_request
jobs:
  dotnet_format:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run Dotnet Format Analyzer
        run: dotnet format analyzers --verbosity diag --report .

      - name: list
        run: |
          ls

      - name: Reviewdog Format Analysis
        run: |
          reviewdog -f=checkstyle -name="Dotnet Format Analyzer" -reporter=github-pr-check format-report.json

      - name: Execute Dotnet Format Analyzer
        run: dotnet format --check --dry-run > format-report2.json

      - name: list 2
        run: |
          ls

      - name: Reviewdog Format Analysis
        run: |
            reviewdog -f=checkstyle -name="Dotnet Format Analyzer" -reporter=github-pr-check format-report2.json

#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.x'
#
#      - name: Install dependencies
#        run: |
#          pip install requests
#
#      - name: Create comments on PR
#        run: |
#          echo "
#          import json
#          import requests
#
#          github_access_token = \"${{ secrets.GITHUB_TOKEN }}\"
#          github_repo = \"${{ github.GITHUB_REPOSITORY }}\"
#          json_file_path = \"format-report.json\"
#          print ({github_access_token})
#          print ({github_repo})
#
#          def create_pr_comment(pr_number, file_path, line_number, body):
#            headers = {
#              \"Authorization\": f\"Bearer {github_access_token}\",
#              \"Content-Type\": \"application/json\"
#            }
#            data = {
#              \"body\": body,
#              \"path\": file_path,
#              \"position\": line_number
#            }
#            url = f\"https://api.github.com/repos/{github_repo}/pulls/{pr_number}/comments\"
#            response = requests.post(url, headers=headers, data=json.dumps(data))
#            print (response)
#            return response.json()
#
#          with open(json_file_path, \"r\") as json_file:
#            data = json.load(json_file)
#
#          for report in data:
#            file_path = report[\"FilePath\"]
#            line_number = report[\"FileChanges\"][0][\"LineNumber\"]
#            diagnostic_id = report[\"FileChanges\"][0][\"DiagnosticId\"]
#            description = report[\"FileChanges\"][0][\"FormatDescription\"]
#            comment_body = f\"Warning {diagnostic_id}: {description}\"
#            pr_number = \"${{ github.event.pull_request.number }}\"
#
#          create_pr_comment(pr_number, file_path, line_number, comment_body)" > temp_script.py
#        shell: bash
#
#      - name: Execute Python script
#        run: python temp_script.py

#      - name: Violation Comments Action
#        uses: tomasbjerre/violation-comments-action@master
#        with:
#          parser: STYLECOP
#          regexp: '.*format-report\.json$'

#      - name: Run dotnet format
#        id: format
#        uses: jfversluis/dotnet-format@v1.0.5
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          action: "fix"
#          only-changed-files: false
#          workspace: StyleCop.sln

#      - name: Commit files
#        if: steps.format.outputs.has-changes == 'true'
#        run: |
#          git config --local user.name "github-actions[bot]"
#          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#          git commit -a -m 'Automated dotnet-format update
#          Co-authored-by: ${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.id }}+${{ github.event.pull_request.user.login }}@users.noreply.github.com>'
#
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v3
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          title: '[housekeeping] Automated PR to fix formatting errors'
#          body: |
#            Automated PR to fix formatting errors
#          committer: GitHub <noreply@github.com>
#          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
#          labels: housekeeping
#          assignees: lyncolnms
#          reviewers: lyncolnms
#          branch: housekeeping/code-format

#      - name: Run Dotnet Format Analyzer
#        run: dotnet format analyzers --verbosity diag --verify-no-changes --report .

#      - name: Run dotnet format
#        id: format
#        uses: jfversluis/dotnet-format@v1.0.5
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          only-changed-files: false
#          fail-fast: false