name: Format check on pull request
on: pull_request
jobs:
  dotnet-format:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run Dotnet Format Analyzer
        run: dotnet format analyzers --verbosity diag --report .

      - name: Violation Comments Action
        uses: tomasbjerre/violation-comments-action@master
        with:
          parser: STYLECOP
          regexp: '.*format-report\.json$'

#      - name: Run dotnet format
#        id: format
#        uses: jfversluis/dotnet-format@v1.0.5
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          action: "fix"
#          only-changed-files: false
#          workspace: StyleCop.sln

#      - name: Commit files
#        if: steps.format.outputs.has-changes == 'true'
#        run: |
#          git config --local user.name "github-actions[bot]"
#          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#          git commit -a -m 'Automated dotnet-format update
#          Co-authored-by: ${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.id }}+${{ github.event.pull_request.user.login }}@users.noreply.github.com>'
#
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v3
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          title: '[housekeeping] Automated PR to fix formatting errors'
#          body: |
#            Automated PR to fix formatting errors
#          committer: GitHub <noreply@github.com>
#          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
#          labels: housekeeping
#          assignees: lyncolnms
#          reviewers: lyncolnms
#          branch: housekeeping/code-format

#      - name: Run Dotnet Format Analyzer
#        run: dotnet format analyzers --verbosity diag --verify-no-changes --report .

#      - name: Run dotnet format
#        id: format
#        uses: jfversluis/dotnet-format@v1.0.5
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          only-changed-files: false
#          fail-fast: false