name: Format check on pull request
on: pull_request
jobs:
  dotnet-format:
    runs-on: windows-latest
    steps:
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run Dotnet Format Analyzer
        run: dotnet format analyzers --verbosity diag --verify-no-changes --report .

#      - name: Run dotnet format
#        id: format
#        uses: jfversluis/dotnet-format@v1.0.5
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          only-changed-files: false
#          fail-fast: false

      - name: List items in folder
        run: |
              ls

      - name: Add comments to pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat format-report.json | jq -c '.[]' | while read -r line; do
            body=$(echo "$line" | jq -r '.message')
            path=$(echo "$line" | jq -r '.path')
            position=$(echo "$line" | jq -r '.position')
      
            gh pr review ${{ github.event.pull_request.number }} --comment "$body" --path "$path" --position "$position"
          done