name: Format check on pull request
on: pull_request
env:
  FORMS_PROJECT_PATH: "StyleCop/StyleCop/StyleCop.csproj"
  ANDROID_PROJECT_PATH: "StyleCop/StyleCop.Droid/StyleCop.Droid.csproj"
  iOS_PROJECT_PATH: "StyleCop/StyleCop.iOS/StyleCop.iOS.csproj"
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
jobs:
  dotnet_format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: dotnet restore

      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1.1.1

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Get modified files in PR
        id: modified_files
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > modified_files.txt

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build and analyze modified projects
        run: |
          $modifiedFiles = Get-Content modified_files.txt
          $projectsToBuild = $modifiedFiles -like "*.csproj"

          if ($projectsToBuild.Count -eq 0) {
            echo "No modified projects to build."
            exit 0
          }

          $projectsToBuild | ForEach-Object {
            msbuild $_ -fl -flp:logfile=analyzer.log /v:diag            
          }

#      - name: Execute StyleCop Analyzers and Dotnet Format
#        run: msbuild StyleCop.sln -fl -flp:logfile=analyzer.log /v:diag

      - name: Violation Comments Action
        uses: tomasbjerre/violation-comments-action@master
        with:
          parser: MSBULDLOG
          regexp: '.*analyzer\\.log$'
          keepOldComments: true # remove the old comments, or keep them
          commentTemplate: '{{violation.message}}' # see https://github.com/tomasbjerre/violation-comments-lib
          maxNumberOfViolations: 99 # Will only post this many comments
          severity: WARN # INFO, WARN or ERROR
          commentOnlyChangedContent: true # Comment only if violations in the changed part of PR
          commentOnlyChangedFiles: true # Comment only on the files that are changed in PR
          createSingleFileComments: true # Comment several comments, for each violation
          createCommentWithAllSingleFileComments: false # Create on big comment with all violations

#      - name: Run dotnet format
#        id: format
#        uses: jfversluis/dotnet-format@v1.0.5
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          action: "fix"
#          only-changed-files: false
#          workspace: StyleCop.sln

#      - name: Commit files
#        if: steps.format.outputs.has-changes == 'true'
#        run: |
#          git config --local user.name "github-actions[bot]"
#          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#          git commit -a -m 'Automated dotnet-format update
#          Co-authored-by: ${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.id }}+${{ github.event.pull_request.user.login }}@users.noreply.github.com>'
#
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v3
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          title: '[housekeeping] Automated PR to fix formatting errors'
#          body: |
#            Automated PR to fix formatting errors
#          committer: GitHub <noreply@github.com>
#          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
#          labels: housekeeping
#          assignees: lyncolnms
#          reviewers: lyncolnms
#          branch: housekeeping/code-format

#      - name: Run Dotnet Format Analyzer
#        run: dotnet format analyzers --verbosity diag --verify-no-changes --report .

#      - name: Run dotnet format
#        id: format
#        uses: jfversluis/dotnet-format@v1.0.5
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          only-changed-files: false
#          fail-fast: false
