name: Code Review

on:
  pull_request:
    types: [opened]
jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'

      - name: Install StyleCop.Analyzers
        run: dotnet tool install StyleCop.Analyzers --global --version <versão-desejada>

      - name: Run StyleCop.Analyzers
        run: dotnet build --configuration Release --no-restore --nologo