name: Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
        
      - name: Install dependencies
        run: nuget restore 
        
      - name: Show what's in the directory
        run: |
              ls
      - name: Show what all is in the parent directory
        run: |
              cd ..
              ls
        
      - name: Build
        run: msbuild StyleCop/StyleCop/StyleCop.csproj /t:PackageForAndroid /p:Configuration=Debug
        
      - name: Build
        run: msbuild StyleCop/StyleCop/StyleCop.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild

      #- name: Build Android
        #run: MSBuild /p:Configuration=Debug ./StyleCop/StyleCop.Droid/StyleCop.Droid.csproj
        #run: msbuild StyleCop/StyleCop.csproj /t:PackageForAndroid /p:Configuration=Debug

      #- name: Build iOS
        #run: MSBuild /t:Build /p:Configuration=Debug /p:Platform=iPhone /p:BuildIpa=true ./StyleCop/StyleCop.iOS/StyleCop.iOS.csproj

      - name: Run StyleCop.Analyzers
        run: dotnet build --configuration Release --no-restore --nologo
