name: Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'

      - name: Install Xamarin.iOS SDK
        run: |
          sudo installer -pkg /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Specifications/Xcode.SDK.iPhoneOS14.5.sdk/System/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/Xamarin.iOS.sdk.pkg -target /

      - name: Install Xamarin.Android SDK
        run: |
          sudo installer -pkg /Applications/Xamarin.Android.sdk/Contents/Resources/Xamarin.Android.sdk.pkg -target /

      - name: Run StyleCop.Analyzers
        run: dotnet build --configuration Release --no-restore --nologo
