name: Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'

      - name: Install Xamarin.iOS SDK
        run: sudo $RUNNER_TOOL_CACHE/Xamarin.iOS/14.20.0.24/xamarin.ios-14.20.0.24.pkg

      - name: Install Xamarin.Android SDK
        run: sudo $RUNNER_TOOL_CACHE/Xamarin.Android/11.4.0.2/xamarin.android-11.4.0.2.pkg

      - name: Run StyleCop.Analyzers
        run: dotnet build --configuration Release --no-restore --nologo