name: Code Review

on:
  pull_request:
    types: [opened]
jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove obj and bin folders
        run: |
          rm -rf **/obj
          rm -rf **/bin

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'

      - name: Clean project
        run: dotnet clean --configuration Release

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Run StyleCop.Analyzers
        run: dotnet build --configuration Release --no-restore --nologo