name: Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: macos-latest

    steps:
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: nuget restore

      - name: Build Android
        run: MSBuild /p:Configuration=Debug ./StyleCop.Android/StyleCop.Android.csproj
        #run: msbuild StyleCop/StyleCop.csproj /t:PackageForAndroid /p:Configuration=Debug

      - name: Build
        run: MSBuild /t:Build /p:Configuration=Debug /p:Platform=iPhone /p:BuildIpa=true ./StyleCop.iOS/StyleCop.iOS.csproj

      - name: Run StyleCop.Analyzers
        run: dotnet build --configuration Release --no-restore --nologo
